version: "2"
services:
  web:
    build: ../
    restart: always
    ports:
    - "7001:7001"
    depends_on:
    - mongo
  mongo:
    image: mongo
     volumes:
     - "../data:/data/db"
     - "/etc/localtime:/etc/localtime"
    ports:
    - "27019:27017"